/*
 * PrintDialog.cs - Implementation of "System.Windows.Forms.PrintDialog" class.
 *
 * Copyright (C) 2004  Southern Storm Software, Pty Ltd.
 * 
 * Autogenerated by csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

using System;
using System.Drawing;
using System.Drawing.Printing;

namespace System.Windows.Forms
{
	[TODO]
	public sealed class PrintDialog : CommonDialog
	{
		private bool allowPrintToFile;
		private bool allowSelection;
		private bool allowSomePages;
		private bool showHelp;
		private bool printToFile;
		private bool showNetwork;
		private PrintDocument printDocument;
		private PrinterSettings printerSettings;

		[TODO]
		public PrintDialog()
		{
			allowPrintToFile = true;
			allowSelection = true;
			allowSomePages = false;
			printDocument = null;
			printToFile = false;
			showHelp = false;
			showNetwork = true;
			printerSettings = null;
		}

		[TODO]
		public override void Reset()
		{
			throw new NotImplementedException("Reset");
		}

		[TODO]
		protected override bool RunDialog(IntPtr hwndOwner)
		{
			throw new NotImplementedException("RunDialog");
		}

		[TODO]
		public bool AllowPrintToFile 
		{
 			get
			{
				return allowPrintToFile;
			}

 			set
			{
				allowPrintToFile = value;
			}

 		}

		[TODO]
		public bool AllowSelection 
		{
 			get
			{
				return allowSelection;
			}

 			set
			{
				allowSelection = value;
			}

 		}

		[TODO]
		public bool AllowSomePages 
		{
 			get
			{
				return allowSomePages;
			}

 			set
			{
				allowSomePages = value;
			}

 		}

		[TODO]
		public PrintDocument Document 
		{
 			get
			{
				return printDocument;
			}

 			set
			{
				printDocument = value;
			}

 		}

		[TODO]
		public bool PrintToFile 
		{
 			get
			{
				return printToFile;
			}

 			set
			{
				printToFile = value;
			}

 		}

		[TODO]
		public PrinterSettings PrinterSettings 
		{
 			get
			{
				return printerSettings;
			}

 			set
			{
				printerSettings = value;
			}

 		}

		[TODO]
		public bool ShowHelp 
		{
 			get
			{
				return showHelp;
			}

 			set
			{
				showHelp = value;
			}

 		}

		[TODO]
		public bool ShowNetwork 
		{
 			get
			{
				return showNetwork;
			}

 			set
			{
				showNetwork = value;
			}

 		}

	}
}//namespace
