/*
 * XmlSchemaComplexType.cs - Implementation of "System.Xml.Schema.XmlSchemaComplexType" 
 *
 * Copyright (C) 2003  Southern Storm Software, Pty Ltd.
 * Copyright (C) 2003  FSF.
 * 
 * Authors : Autogenerated using csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

namespace System.Xml.Schema
{
	public class XmlSchemaComplexType: XmlSchemaType
	{
		[TODO]
		public XmlSchemaComplexType()
		{
			 throw new NotImplementedException(".ctor");
		}

		[TODO]
		public System.Xml.Schema.XmlSchemaAnyAttribute AnyAttribute 
		{
 			get
			{
				throw new NotImplementedException("AnyAttribute");
			}
 			set
			{
				throw new NotImplementedException("AnyAttribute");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaObjectTable AttributeUses 
		{
 			get
			{
				throw new NotImplementedException("AttributeUses");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaAnyAttribute AttributeWildcard 
		{
 			get
			{
				throw new NotImplementedException("AttributeWildcard");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaObjectCollection Attributes 
		{
 			get
			{
				throw new NotImplementedException("Attributes");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaDerivationMethod Block 
		{
 			get
			{
				throw new NotImplementedException("Block");
			}
 			set
			{
				throw new NotImplementedException("Block");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaDerivationMethod BlockResolved 
		{
 			get
			{
				throw new NotImplementedException("BlockResolved");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaContentModel ContentModel 
		{
 			get
			{
				throw new NotImplementedException("ContentModel");
			}
 			set
			{
				throw new NotImplementedException("ContentModel");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaContentType ContentType 
		{
 			get
			{
				throw new NotImplementedException("ContentType");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaParticle ContentTypeParticle 
		{
 			get
			{
				throw new NotImplementedException("ContentTypeParticle");
			}
 		}

		[TODO]
		public bool IsAbstract 
		{
 			get
			{
				throw new NotImplementedException("IsAbstract");
			}
 			set
			{
				throw new NotImplementedException("IsAbstract");
			}
 		}

		[TODO]
		public override bool IsMixed 
		{
 			get
			{
				throw new NotImplementedException("IsMixed");
			}
 			set
			{
				throw new NotImplementedException("IsMixed");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaParticle Particle 
		{
 			get
			{
				throw new NotImplementedException("Particle");
			}
 			set
			{
				throw new NotImplementedException("Particle");
			}
 		}

	}
}//namespace