/*
 * XmlSchemaDocumentation.cs - Implementation of "System.Xml.Schema.XmlSchemaDocumentation" 
 *
 * Copyright (C) 2003  Southern Storm Software, Pty Ltd.
 * Copyright (C) 2003  FSF.
 * 
 * Authors : Autogenerated using csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

namespace System.Xml.Schema
{
	public class XmlSchemaDocumentation: XmlSchemaObject
	{
		[TODO]
		public XmlSchemaDocumentation()
		{
			 throw new NotImplementedException(".ctor");
		}

		[TODO]
		public System.String Language 
		{
 			get
			{
				throw new NotImplementedException("Language");
			}
 			set
			{
				throw new NotImplementedException("Language");
			}
 		}

		[TODO]
		public System.Xml.XmlNode[] Markup 
		{
 			get
			{
				throw new NotImplementedException("Markup");
			}
 			set
			{
				throw new NotImplementedException("Markup");
			}
 		}

		[TODO]
		public System.String Source 
		{
 			get
			{
				throw new NotImplementedException("Source");
			}
 			set
			{
				throw new NotImplementedException("Source");
			}
 		}

	}
}//namespace