/*
 * XmlSchemaAnnotation.cs - Implementation of "System.Xml.Schema.XmlSchemaAnnotation" 
 *
 * Copyright (C) 2003  Southern Storm Software, Pty Ltd.
 * Copyright (C) 2003  FSF.
 * 
 * Authors : Autogenerated using csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

namespace System.Xml.Schema
{
	public class XmlSchemaAnnotation: XmlSchemaObject
	{
		[TODO]
		public XmlSchemaAnnotation()
		{
			 throw new NotImplementedException(".ctor");
		}

		[TODO]
		public System.String Id 
		{
 			get
			{
				throw new NotImplementedException("Id");
			}
 			set
			{
				throw new NotImplementedException("Id");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaObjectCollection Items 
		{
 			get
			{
				throw new NotImplementedException("Items");
			}
 		}

		[TODO]
		public System.Xml.XmlAttribute[] UnhandledAttributes 
		{
 			get
			{
				throw new NotImplementedException("UnhandledAttributes");
			}
 			set
			{
				throw new NotImplementedException("UnhandledAttributes");
			}
 		}

	}
}//namespace