/*
 * XmlSchemaObjectTable.cs - Implementation of "System.Xml.Schema.XmlSchemaObjectTable" 
 *
 * Copyright (C) 2003  Southern Storm Software, Pty Ltd.
 * Copyright (C) 2003  FSF.
 * 
 * Authors : Autogenerated using csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

namespace System.Xml.Schema
{
	public class XmlSchemaObjectTable
	{
		[TODO]
		public bool Contains(System.Xml.XmlQualifiedName name)
		{
			 throw new NotImplementedException("Contains");
		}

		[TODO]
		public System.Collections.IDictionaryEnumerator GetEnumerator()
		{
			 throw new NotImplementedException("GetEnumerator");
		}

		[TODO]
		public int Count 
		{
 			get
			{
				throw new NotImplementedException("Count");
			}
 		}

		[TODO]
		public System.Xml.Schema.XmlSchemaObject this[System.Xml.XmlQualifiedName name] 
		{
 			get
			{
				throw new NotImplementedException("Item");
			}
 		}

		[TODO]
		public System.Collections.ICollection Names 
		{
 			get
			{
				throw new NotImplementedException("Names");
			}
 		}

		[TODO]
		public System.Collections.ICollection Values 
		{
 			get
			{
				throw new NotImplementedException("Values");
			}
 		}

	}
}//namespace