.\" Copyright (c) 2001 Southern Storm Software, Pty Ltd.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.TH csdoc2html 1 "27 September 2001" "Southern Storm Software" "Portable.NET Development Tools"
.SH NAME
csdoc2html \- convert C# documentation into HTML
.SH SYNOPSIS
\fBcsdoc2html\fR [ options ] \fIinput\fR ...
.SH DESCRIPTION
.B Csdoc2html
reads the supplied XML input files, and converts them into
a collection of HTML files.  This collection can be viewed
using a standard Web browser.

Specifying multiple input files is exactly the same as specifying
one input file which is the concatenation of all of the files.
Only one output collection is created.  \fBCsdoc2html\fR must be invoked
multiple times to convert multiple input files into multiple output
collections.
.SH OPTIONS
.TP
.B -o \fIdir\fR, \-\-output \fIdir\fR
Specify the name of the directory to write the HTML output to
in multi-file mode (the default).  The default is the current
directory.
.TP
.B -o \fIfile\fR, \-\-output \fIfile\fR
Specify the name of the file to write the HTML output to
in single-file mode.  The default is `input.html'.  If there are
multiple input files, then the name of the output file is based on
the name of the first input file.  If the first input file is `\-',
then the output is written to standard output.  If \fIfile\fR is `\-',
then the output is written to standard output.
.TP
.B \-fsingle\-file
Write all HTML data to a single output file, rather than splitting
the data across multiple files.
.TP
.B \-fmulti\-file
Split the HTML data across multiple output files.  The file
`index.html' in the output directory is the main entry point
to browse the collection.  This is the default.
.TP
.B \-fframes
Use HTML frames when writing the output data in multi-file mode.
This is the default.
.TP
.B \-fno\-frames
Do not use HTML frames when writing the output data in multi-file mode.
.TP
.B \-fcombine\-members
Combine the documentation for type members into the same output
file as the type itself.  This is the default.
.TP
.B \-fseparate\-members
Separate the documentation for type members into distinct output files.
.TP
.B \-fnamespace\-directories
Write the contents of each namespace into a separate sub-directory.
This is the default.
.TP
.B \-fno\-namespace\-directories
Write the contents of all namespaces into the primary output
directory, and do not create any sub-directories.
.TP
.B \-ftitle=\fItitle\fR
Specify the title to use for the collection.  The default is
the same as the first input filename.
.TP
.B \-fpage\-color=\fIcolor\fR
Specify the HTML color value to use for the background of pages.
The default is `#FFFFFF'.
.TP
.B \-fdefn\-color=\fIcolor\fR
Specify the HTML color value to use for the background of
type and member definitions.  The default is `#C0C0C0'.
.TP
.B \-fheader\-color=\fIcolor\fR
Specify the HTML color value to use for the background of
table headers.  The default is `#C0C0C0'.
.TP
.B \-\-help
Print a usage message for the \fBcsdoc2html\fR program.
.TP
.B \-v, \-\-version
Print the version of the \fBcsdoc2html\fR program.
.TP
.B \-\-
Marks the end of the command-line options, and the beginning of
the input filenames.  You may need to use this if your filename
begins with '-'.  e.g. "csdoc2html -- -input.xml".  This is not needed
if the input is stdin: "csdoc2html -" is perfectly valid.
.SH "AUTHOR"
Written by Southern Storm Software, Pty Ltd.

http://www.southern-storm.com.au/
.SH "SEE ALSO"
csdoc(1), csdoc2texi(1)
.SH "DIAGNOSTICS"
Exit status is 1 if an error occurred while processing the input.
Otherwise the exit status is 0.
